chore: deploy to custom domain

diff --git a/.github/workflows/dev-deploy.yml b/.github/workflows/dev-deploy.yml
--- a/.github/workflows/dev-deploy.yml
+++ b/.github/workflows/dev-deploy.yml
@@ -9,7 +9,7 @@ on:
     branches:
       - develop
 jobs:
-  Deploy-Preview:
+  preview-deploy:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
@@ -19,5 +19,18 @@ jobs:
         run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
       - name: Build Project Artifacts
         run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
-      - name: Deploy Project Artifacts to Vercel
-        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
+      - name: Deploy & Alias to Custom Domain
+        run: |
+          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} \
+            > deployment-url.txt 2> error.txt
+
+          code=$?
+          if [ $code -eq 0 ]; then
+            deploymentUrl=$(cat deployment-url.txt)
+            vercel alias $deploymentUrl dev-react-native-todo-one.vercel.app \
+              --token=${{ secrets.VERCEL_TOKEN }}
+          else
+            echo "Vercel deploy failed"
+            cat error.txt
+            exit 1
+          fi
